DROP TABLE IF EXISTS weather_data CASCADE;

-- db/schema/weather_data.sql
CREATE TABLE IF NOT EXISTS weather_data (
  ID SERIAL PRIMARY KEY NOT NULL,
  CITY VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  TEMPERATURE DOUBLE PRECISION,
  HUMIDITY INT,
  VISIBILITY INT,
  PRESSURE INT,
  WIND DOUBLE PRECISION,
  WIND_DIRECTION TEXT,
  SUNRISE TIME,
  SUNSET TIME,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



